[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vsat"
version = "0.1.0"
authors = [
  { name="wangfff8", email="wffhznu825@163.com" },
]
description = "A tool for analyzing Single Nucleotide Polymorphisms (SNPs) in viral genomes."
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.hatch.build.target.wheel]
package = "vsat"
