name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "latest"

      - name: Set up Python venv with uv
        run: uv venv
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          . venv/bin/activate
          uv pip install -e .
          uv pip install ruff mypy

      - name: Run Ruff (Linting)
        run: ruff check .

      - name: Run Mypy (Type Checking)
        run: mypy src/vsat

      - name: Build package
        run: uv build
